' PlantUML
@startuml cd

title An example of Continuous Deployment using GitDocumentDB

node "GitHub" {
  database "Generator Git repository\n(sosuisen-my-inventory-gatsby)" as generatorrepos  #f0fff0;line:green{
    component "build scripts"  #ffffff{
      component "gatsby build" as gatsby
      component "git submodule" as submodule #fff0f0;line:red;line.dashed;{
        collections "JSON files" as repjson #3030f0;text:white
      }
    }
    component "Gatsby" {
      component "gatsby-source-filesystem" {
        component "gatsby-transformer-json" as transformer
      }
    }
  }
  database "Source Git repository\n(sosuisen-my-inventory)" as sourcerepos #fff0f0;line:red{
    collections "JSON files" as json #3030f0;text:white
    component "GitHub actions\non push" as githubaction #ffffff{
      agent "curl" as curl
    }
  }
}

sourcerepos -0)- submodule : "update --remote"
submodule -0)- transformer

node "Local App\n(Inventory Manager)" {
  database "GitDocumentDB" #f0f0ff{
    database "Local Git repository" as localrepos {
      collections "JSON files" as localjson #3030f0;text:white
    }
  }
}

localrepos -(0)- sourcerepos : Synchronize (push and pull)

node "Netlify" {
  component "Static website" as website {
    component "Build hooks" as buildhooks
  }
}

curl -(0- buildhooks : POST
buildhooks -(0- generatorrepos : build

@enduml